apiVersion: v1
kind: Pod
metadata:
  name: app-with-logger
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'while true; do echo "$(date) App is running" >> /logs/app.log; sleep 2; done']
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - name: shared-logs
          mountPath: /logs
    - name: logger
      image: busybox
      command: ['sh', '-c', 'tail -f /logs/app.log']
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "64Mi"
          cpu: "100m"
      volumeMounts:
        - name: shared-logs
          mountPath: /logs  