apiVersion: v1
kind: Pod
metadata:
    name: init-app-demo
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "Hello from Init Container" > /shared/message.txt']
      volumeMounts:
        - name: shared-data
          mountPath: /shared
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  containers:
    - name: main-app
      image: busybox
      command: ['sh', '-c', 'cat /shared/message.txt && sleep 3600']
      volumeMounts:
        - name: shared-data
          mountPath: /shared
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"