apiVersion: v1
kind: Pod
metadata:
  name: ambassador-demo
spec:
  containers:
    - name: app
      image: curlimages/curl:latest
      command: ['sh', '-c', 'while true; do sleep 10 && curl -s http://localhost:8080/api && sleep 5; done']
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    - name: ambassador
      image: busybox
      command: ['sh', '-c', 'while true; do echo -e "HTTP/1.1 200 OK\r\n\r\nAPI Key Injected" | nc -l -p 8080; done']
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"