apiVersion: v1
kind: Pod
metadata:
  name: adapter-demo
spec:
  volumes:
    - name: data-volume
      emptyDir: {}
  containers:
    - name: app
      image: busybox
      command: ['sh', '-c', 'echo "{\"name\":\"andrii\"}" > /data/input.json && sleep 3600']
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: adapter
      image: busybox
      command: ['sh', '-c', 'sleep 5 && echo "name,andrii" > /data/output.csv && tail -f /data/output.csv']
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - name: data-volume
          mountPath: /data